### ISSUE TITLE
sports-football-fr and sport-fr packages disambiguation

### ISSUE THREAD

**Issue by letompouce** [ideascube/catalog-i-o#19]
As of [2019, July](https://github.com/ideascube/catalog-i-o/blob/9675e295195b0d5f87f548793994c2d9c3d434fe/omeka.yml#L5955-L5964):
```
  sport-football-fr:
    description: "Vous souhaitez vous perfectionner en football ? D\xE9couvrir un\
      \ nouveau sens au mot \"sport\" ? C'est ici !"
    name: Sports
    url: http://packages.ideascube.org/omeka/sports-fr.zip
```
The package is named `sport-football-fr` but the ZIP file is named `sports-fr`.

This would be misleading enough, but for the vigilants that won't fall, the next package in the list is [`sport-fr`](https://github.com/ideascube/catalog-i-o/blob/9675e295195b0d5f87f548793994c2d9c3d434fe/omeka.yml#L5965-L5974) with `sport-fr.zip` as ZIP file:
```
  sport-fr:
    description: Vous souhaitez vous perfectionner en football ? Vous initier au yoga
      ou faire un exercice physique quotidien ?  C'est ici !
    name: "D\xE9couvrez diff\xE9rents sports"
    url: http://packages.ideascube.org/omeka/sport-fr.zip
```

Both package have a very similar `description`. `sport-football-fr` has a poor `name`.

- [ ] regenerate the `sport-football-fr` package with an accurate ZIP file name
- [ ] Consider rewriting/rewording both packages `description` fields
- [ ] Expand `sport-football-fr`'s `name` field
